"""Editorial and policy content for ClearCV's public website.

This module is intentionally separate from resume generation. Page dictionaries are
rendered by a shared template so metadata, navigation, and internal links remain
consistent without coupling content to the builder.
"""

from __future__ import annotations


def page(title, description, category, intro, sections, related=(), eyebrow=None, faq=()):
    return {
        "title": title, "description": description, "category": category,
        "eyebrow": eyebrow or category.upper(), "intro": intro, "sections": sections,
        "related": list(related), "faq": list(faq),
    }


POLICY_PAGES = {
    "about": page("About ClearCV", "Learn how ClearCV helps job seekers create clear, credible, ATS-friendly resumes while keeping personal data private.", "Company",
        "ClearCV is an independent resume-building platform created around a simple belief: job seekers should be able to present their experience clearly without surrendering control of their personal information or being pushed toward exaggerated claims.", [
        ("Our purpose", "Applying for work is demanding enough without confusing templates, opaque scores, and generic writing. ClearCV combines a focused writing workflow with a predictable single-column document. The builder helps people organize genuine experience, compare relevant language with a job description, and export an editable resume. We do not promise interviews or claim to reproduce an employer's private screening software. Our aim is more practical: improve clarity, relevance, and document readability."),
        ("How we work", "Our guidance is based on established career-center recommendations: use recognizable headings, describe outcomes instead of copying duties, quantify only when the number is true, and tailor each application. The readiness review is transparent and educational. It checks visible factors such as contact details, measurable impact, skills, and role terminology. A person should always review the final document because no automated tool understands a career as well as its owner."),
        ("Privacy by design", "Resume drafts are stored in the user's browser through local storage. ClearCV does not maintain a server-side resume database in the current service. Export requests are processed in memory to create a DOCX or PDF and are not intentionally retained after the response is delivered. We do not sell resume data. More detail is available in our Privacy Policy, including deletion instructions and the limits of internet security."),
        ("Editorial independence", "ClearCV publishes practical guides for readers, not pages written to disguise advertising. Recommendations are reviewed for usefulness, limitations are stated, and job-search outcomes are never guaranteed. If advertising or commercial partnerships are introduced, they will be distinguished from editorial content. We welcome corrections and accessibility feedback through the Contact page."),
    ], related=("privacy-policy", "ats-resume-guide", "contact")),
    "contact": page("Contact ClearCV", "Contact ClearCV for support, privacy requests, corrections, accessibility feedback, or business inquiries.", "Company",
        "Questions should have a clear destination. Use the information below for product support, privacy requests, editorial corrections, accessibility feedback, or legitimate business inquiries.", [
        ("How to reach us", "Email support@clearcv.example with a descriptive subject line such as “Export support,” “Privacy request,” or “Article correction.” This development installation uses an example address and must be replaced with an actively monitored domain mailbox before public launch. Include the browser and device you used for technical issues, but never email passwords, government identification, or unnecessary sensitive information."),
        ("Response expectations", "We aim to acknowledge ordinary support messages within three business days. Privacy and deletion requests receive priority and may require reasonable verification so another person cannot act on your behalf. We cannot contact employers, guarantee application outcomes, or provide legal, immigration, financial, or licensed career-counseling services."),
        ("Useful details", "For an export problem, explain whether DOCX or PDF was affected and which application opened the file. For an editorial correction, include the page URL and the sentence at issue. For accessibility feedback, describe the assistive technology and the task you were trying to complete. Clear, limited details help us investigate without collecting more personal information than necessary."),
    ], related=("faq", "privacy-policy", "about")),
    "privacy-policy": page("Privacy Policy", "Read how ClearCV handles resume drafts, export files, analytics, cookies, deletion requests, retention, and security.", "Legal",
        "Effective August 6, 2026. This policy explains what ClearCV processes, why it is processed, how long it is kept, and the choices available to users. It should be read before entering personal information into the builder.", [
        ("Information you provide", "The builder may process contact details, employment history, education, skills, project information, languages, and a pasted job description. In the current version, draft fields are saved in local storage within your browser so you can return to them. They are not submitted to our server until you request analysis or an export. Do not enter government identifiers, financial account data, health records, references' private details, or information you do not have permission to use."),
        ("Processing and purpose", "When you request analysis, the submitted text is used to calculate a transparent keyword and completeness review. When you request an export, the server uses the submitted data to assemble a DOCX or text-based PDF in memory and return it to your browser. Processing is necessary to provide the requested feature. We do not use resume contents to build advertising profiles, sell them, or intentionally train models on them."),
        ("Optional AI resume tailoring", "The Resume Tailor accepts a DOCX resume and pasted job description. The file is parsed in memory. When the site operator configures AI mode, extracted resume text and the job description are transmitted to the configured Hugging Face inference provider so it can produce a structured rewrite. That provider processes data under its own terms, security measures, and retention practices. The upload page discloses the active mode. Without AI configuration, the source wording is reformatted locally on the application server and is not sent to an AI provider."),
        ("File retention and deletion", "ClearCV does not intentionally keep uploaded or generated resume files in the current architecture. In-memory export data is released after the response. Browser drafts remain on your device until you clear site data, use private browsing, or remove local storage through browser settings. A future account or cloud-storage feature would require an updated policy and an explicit retention period before launch. To request deletion of any support record associated with you, contact the address on our Contact page."),
        ("Logs, analytics, cookies, and advertising", "Web infrastructure may record limited technical logs such as IP address, request time, browser type, route, and error details for reliability and abuse prevention. Production retention limits must be configured with the hosting provider. ClearCV currently needs local storage for drafts but does not require an advertising cookie to build a resume. If analytics, consent-managed advertising, or Google AdSense is enabled, this policy and the consent interface must be updated before collection begins."),
        ("Security", "We minimize collection, avoid a resume database, escape displayed user content, and generate documents server-side from validated fields. Production deployment should enforce HTTPS, secure headers, dependency updates, access controls, monitoring, backups for essential business records, and a tested incident-response process. No internet transmission or storage system is perfectly secure; users should remove unnecessary sensitive details and protect downloaded files on their own devices."),
        ("Your rights and international use", "Depending on location, users may have rights to access, correct, delete, restrict, or object to processing and to complain to a supervisory authority. Contact us to exercise an applicable right. ClearCV is accessible internationally, but this development policy does not by itself satisfy every jurisdiction. Before production, the operator must publish its legal identity, physical or registered address, applicable data controller details, and any required regional disclosures."),
        ("Changes", "Material changes will be posted on this page with a revised effective date. Continued use after a change does not remove rights that require consent under applicable law. Questions may be sent through the Contact page."),
    ], related=("terms", "contact", "about")),
    "terms": page("Terms of Service", "Review the rules, responsibilities, limitations, and acceptable-use terms for using ClearCV.", "Legal",
        "Effective August 6, 2026. By using ClearCV, you agree to these terms. If you do not agree, do not use the service. These terms are written for the current free, browser-based builder and require legal review before commercial launch.", [
        ("Service and eligibility", "ClearCV provides writing guidance, document formatting, keyword comparison, and resume exports. You must be legally able to enter an agreement in your jurisdiction or use the service with appropriate guardian permission. You are responsible for the accuracy and legality of information you enter and for reviewing every application before submission."),
        ("No employment guarantee", "A readiness score is an educational indicator, not certification, legal advice, recruiter approval, or a prediction of hiring. Applicant tracking systems differ and employers consider many factors. ClearCV cannot guarantee parsing, ranking, interviews, offers, compensation, or any other employment outcome."),
        ("Acceptable use", "Do not use the service to impersonate someone, invent credentials, violate privacy or intellectual-property rights, distribute malware, probe security, overload infrastructure, automate abusive requests, or create discriminatory or unlawful hiring materials. Do not submit confidential employer information or another person's data without authority."),
        ("Ownership", "Users retain rights in the truthful content they provide. ClearCV retains rights in its software, branding, page design, original guides, and documentation. The generated document is provided for the user's personal job-search use. Third-party names and trademarks remain the property of their owners."),
        ("Availability and liability", "The service may change, experience errors, or be interrupted. To the extent permitted by law, it is provided without warranties of uninterrupted availability, fitness for a particular job application, or universal ATS compatibility. The operator is not liable for indirect, incidental, or consequential loss arising from use, inability to use, or reliance on the service. Rights that cannot legally be excluded remain unaffected."),
        ("Changes and contact", "We may update these terms when the service changes. Material revisions will receive a new effective date. The production operator must add its legal name, governing law, venue, and required consumer disclosures before accepting paid customers. Questions should be sent through the Contact page."),
    ], related=("privacy-policy", "refund-policy", "faq")),
    "refund-policy": page("Refund Policy", "Understand ClearCV's current free-service policy and how future paid-plan refund requests would be handled.", "Legal",
        "ClearCV's current builder does not charge users, so there is presently no purchase to refund. This page explains that status clearly and establishes the disclosures required before a paid plan can be offered.", [
        ("Current free service", "No payment information is collected by the application described on this website. Creating, reviewing, and exporting a resume is currently free. A message requesting payment outside an official future checkout should be treated as suspicious and reported through the Contact page."),
        ("Before paid plans launch", "Pricing, billing interval, taxes, renewal behavior, included features, cancellation controls, trial conditions, and refund eligibility must be displayed before checkout. The final policy must identify the merchant of record and payment processor. Paid functionality should not launch until those details and legally required cancellation rights are implemented."),
        ("Future refund requests", "If paid plans are introduced, users should contact support with the account email, transaction reference, purchase date, and concise reason. Never send full card numbers. Any future refund window shown at checkout will control, subject to mandatory consumer rights. Duplicate charges, unauthorized transactions, and service failures will be investigated promptly."),
        ("Digital exports", "A downloaded resume is a digital output assembled from user-provided information. Future pricing may distinguish between subscription access and one-time exports. Limitations for consumed digital services must be disclosed before purchase and cannot override rights that apply by law."),
    ], related=("pricing", "terms", "contact")),
    "pricing": page("Simple Resume Builder Pricing", "See what is included in ClearCV's free ATS resume builder and how future plans will be disclosed.", "Product",
        "ClearCV is currently free. You can build a resume, compare it with a job description, save a local draft, and export DOCX and PDF files without creating an account.", [
        ("Free access", "The current plan includes the complete five-step builder, live single-column preview, transparent readiness checks, local browser draft storage, and both editable Word and text-based PDF exports. There is no hidden trial, credit-card requirement, recurring subscription, or paywall in this version."),
        ("What a score means", "The ATS indicator reviews visible document factors; it is not a paid promise of employer approval. Improving a score should never mean inserting a skill you do not possess. ClearCV keeps the explanation visible so users can decide which suggestions truthfully apply."),
        ("Future plans", "If optional paid services are introduced, this page will state exact prices, currency, tax treatment, renewal terms, limits, and cancellation instructions before checkout. Free and paid capabilities will be compared plainly. No paid plan is currently available, and ClearCV does not accept payment information."),
    ], related=("refund-policy", "faq", "ats-resume-guide")),
    "faq": page("Frequently Asked Questions", "Answers about ATS resumes, privacy, exports, scores, tailoring, document formats, and ClearCV features.", "Support",
        "These answers cover the practical questions people ask before building and submitting a resume. They also explain where automated checks end and personal judgment begins.", [], related=("ats-resume-guide", "privacy-policy", "contact"), faq=(
        ("Is ClearCV free?", "Yes. The current builder, readiness review, local draft, DOCX export, and PDF export are free and require no account."),
        ("Does ClearCV guarantee an ATS pass?", "No. There is no universal pass score, and private systems differ. ClearCV checks readable structure, completeness, relevant terminology, and evidence-based writing."),
        ("Where is my resume stored?", "The draft is stored in local browser storage. Data is sent to the server when analysis or export is requested, processed for that request, and not intentionally retained as a resume file."),
        ("Can I delete my draft?", "Yes. Clear the site data or local storage for ClearCV in browser settings. Private browsing usually removes local data when the session closes."),
        ("Should I download DOCX or PDF?", "Follow the employer's requested format. DOCX is editable and widely parsed. A text-based PDF preserves appearance. ClearCV provides both."),
        ("Why paste the job description?", "It lets the readiness review identify important terminology that appears in both texts. Add missing language only when it truthfully describes your experience."),
        ("Does ClearCV write fake achievements?", "No. The builder prompts you to describe real actions and results and warns against inventing metrics or credentials."),
        ("How long should my resume be?", "One page often works for early-career candidates; two pages can be appropriate for substantial relevant experience. Relevance and readability matter more than forcing a page count."),
        ("Can I use ClearCV outside the United States?", "Yes, but conventions differ. Review local expectations for photos, personal details, spelling, page size, and the distinction between a resume and academic CV."),
        ("How do I report a problem?", "Use the Contact page and include the affected export type, browser, device, and a description without unnecessary sensitive information."),
    )),
}


GUIDE_SPECS = {
    "ats-resume-guide": ("ATS Resume Guide", "Build an ATS-friendly resume with clean structure, relevant keywords, credible achievements, and reliable file formatting.", "Create a resume that software can parse and a recruiter can trust.", [
        ("What ATS-friendly really means", "An applicant tracking system stores applications and helps recruiting teams search, filter, and organize candidates. ATS-friendly does not mean gaming an algorithm or repeating a job title until a hidden score rises. It means presenting truthful qualifications in predictable text: an identifiable name and contact block, conventional section headings, dated employment, education, skills, and plain achievement bullets. The same choices that help parsing usually help a hurried human reader. A clean document reduces ambiguity; it does not compensate for missing qualifications."),
        ("Choose a dependable structure", "Use one main column and a reverse-chronological or combination format. Put recent, relevant experience first. Headings such as Professional Summary, Core Skills, Professional Experience, Projects, Education, and Languages communicate more reliably than clever labels. Avoid putting essential details in headers, footers, floating text boxes, charts, icons, or images. Use a standard font, restrained sizes, consistent month-and-year dates, and ordinary round bullets. A decorative portfolio can be a separate document when the field values visual work."),
        ("Tailor language without keyword stuffing", "Read the posting for repeated responsibilities, tools, methods, credentials, and business outcomes. Separate mandatory qualifications from preferences. Where the employer's term accurately describes your background, use that recognized term in a summary, skill list, or evidence bullet. Do not paste a hidden keyword block, repeat terms unnaturally, or claim unfamiliar tools. Include both an abbreviation and its expanded form when useful, such as customer relationship management (CRM), but prioritize natural sentences."),
        ("Write evidence-rich bullets", "A strong bullet connects an action to scope and outcome. Start with a precise verb, name what you improved or delivered, explain relevant constraints, and add a verified measure when available. “Managed reports” is vague; “Automated the monthly revenue report in Python, reducing preparation from two days to three hours” shows method and result. Numbers can describe time, volume, adoption, quality, revenue, cost, or team size. When no metric exists, describe a concrete deliverable, stakeholder decision, or operational change instead of inventing one."),
        ("Export and test the file", "Follow the employer's file instruction above any general recommendation. DOCX is editable and common; a properly generated text-based PDF preserves layout. Name the file professionally with your name and target role. After export, select and copy the text into a plain editor. Confirm that the reading order is sensible, characters are intact, dates remain associated with jobs, and links show meaningful text. Open the file on another device and proofread the final artifact rather than relying only on a browser preview."),
        ("A practical final review", "Check spelling, tense, punctuation, date consistency, contact accuracy, and link destinations. Confirm that every prominent skill is supported by experience, education, or a project. Remove outdated or irrelevant detail before shrinking the font. Ask a trusted reader whether the target role is obvious within ten seconds and which three results stand out. Save a master resume containing your full history, then create a separate tailored copy for each application. ClearCV supports this workflow without pretending a private employer system can be perfectly simulated."),
    ]),
    "how-ats-systems-work": ("How ATS Systems Work", "Understand how applicant tracking systems collect, parse, search, rank, and present resumes to recruiting teams.", "Learn what happens after you upload a resume—and which parts you can responsibly control.", [
        ("The system behind the application", "An applicant tracking system is primarily a recruiting database and workflow tool. Employers use it to publish openings, receive applications, record consent, route candidates, schedule interviews, collect feedback, and document decisions. Resume screening is one feature among many. Products and employer configurations vary widely, so claims about a single universal algorithm or automatic rejection score should be treated cautiously. A candidate can control document clarity and relevance but cannot know every private rule."),
        ("Ingestion and parsing", "After upload, the system stores the original file and may extract a text version. A parser tries to identify contact information, job titles, employers, dates, education, skills, and sections. Clear headings and a logical reading order give it stronger signals. Complex columns, overlapping objects, scanned images, unusual glyphs, and important text in decorative regions can create extraction errors. Modern parsers are capable, but a text-based, conventional document remains a sensible low-risk choice."),
        ("Search, filters, and matching", "Recruiters may filter by application answers, location, authorization, certifications, dates, or other job requirements. They may search for terms associated with the position or use matching features supplied by the platform. Context matters: a keyword in an achievement is more informative than the same word in a disconnected list. Some decisions are based on knockout questions completed outside the resume. Accurate application-form answers therefore matter as much as document formatting."),
        ("Ranking is not universal", "Some systems offer recommendations or relevance signals, while others simply display candidates in a queue. Employers configure processes differently and recruiters can override, sort, or search results. The popular idea that every resume receives one definitive ATS score oversimplifies this environment. Public resume checkers can highlight useful issues, but their percentage is not the employer's result. Treat a score as a checklist, never as proof that an application will advance."),
        ("What the recruiter sees", "A recruiter may view extracted profile fields, application answers, the original resume, activity history, and internal notes. If parsing assigns an employer name to the wrong date, the original file may still be available, but the error creates friction. This is why consistent experience entries matter. Recruiters also evaluate evidence, career progression, communication, and alignment with the actual work—qualities no keyword count can establish on its own."),
        ("A responsible optimization strategy", "Start with the real requirements and decide whether the role fits. Use the posting's terminology where accurate, provide dated evidence, keep the file readable, and complete every required application field. Do not manipulate white text, copy the entire description, or misrepresent experience. Test extracted text and maintain a master history so tailoring means selecting relevant evidence rather than reinventing your background. The best preparation serves both the system and the person who ultimately reviews the application."),
    ]),
    "resume-writing-tips": ("Resume Writing Tips", "Write a focused professional resume with a strong summary, credible achievements, relevant skills, and concise experience.", "Turn a career history into a focused argument for the next role.", [
        ("Begin with the reader's decision", "A resume is not an autobiography. It is a selective document that helps an employer decide whether a conversation is worthwhile. Before drafting, write down the target role, its central problems, and the evidence that proves you can address them. Keep a private master inventory of roles, projects, training, recognition, tools, and outcomes. Tailoring then becomes an editing task: choose the strongest relevant proof and remove detail that competes for attention."),
        ("Make the opening specific", "A professional summary should identify your field, level or scope of experience, strongest relevant capabilities, and the value you create. Replace generic adjectives with useful nouns and evidence. “Motivated professional seeking growth” could describe anyone. “Operations coordinator experienced in vendor onboarding, inventory controls, and weekly reporting across three retail locations” gives the reader a concrete frame. Write the summary after the experience section so it reflects what the document actually supports."),
        ("Build achievement bullets", "Interview your own experience. What was slow, risky, expensive, confusing, or underperforming before your action? What did you personally change? Who used the result? How was improvement observed? Convert the answers into concise action-and-outcome bullets. Vary verbs according to the work—analyzed, negotiated, reconciled, designed, coached, launched—rather than starting every line with “responsible for.” Use past tense for completed work and present tense for continuing responsibilities."),
        ("Use numbers honestly", "Metrics make scope visible, but only when they are defensible. Look for counts, frequency, time saved, error rate, satisfaction, conversion, delivery speed, budget, portfolio size, or team reach. If exact commercial results are confidential, use an approved range or describe the operational outcome without disclosure. Never reverse-engineer an impressive number. A specific nonnumeric statement about a process adopted by leadership is stronger than a fabricated percentage."),
        ("Edit for relevance and rhythm", "Place the most relevant bullet first within each job. Remove repeated claims and combine overlapping duties. Prefer direct sentences, concrete nouns, and familiar industry language. Keep bullet length controlled; two dense lines are often easier to scan than a paragraph. Read the document aloud to find inflated phrases and missing words. Then review only dates, only punctuation, and only capitalization in separate passes—focused proofreading catches inconsistencies that normal reading skips."),
        ("Finish with presentation", "Use a single main column, standard headings, consistent spacing, and sufficient white space. Keep contact details current and links professional. Order sections according to evidence: experienced applicants usually lead with experience, while a recent graduate may position education or projects earlier. Export in the requested format, inspect the actual file, and ask someone unfamiliar with your history to identify the target role and strongest outcomes. If they cannot, revise hierarchy before adding more content."),
    ]),
    "common-resume-mistakes": ("Common Resume Mistakes", "Avoid resume mistakes that weaken ATS parsing, recruiter trust, relevance, readability, and professional credibility.", "Find the problems that make a qualified candidate harder to understand.", [
        ("Writing one resume for every role", "A broad master resume is useful, but sending it unchanged makes the reader search for relevance. Different roles value different evidence. Tailoring does not require rewriting history; it means selecting the projects, skills, outcomes, and terminology most connected to the posting. Create a named copy for each opportunity, preserve truthful dates and employers, and reorder bullets so the strongest fit appears first."),
        ("Listing duties without outcomes", "Job descriptions explain what a position was expected to do, not how well you did it. Bullets such as “answered calls” or “worked on software” lack scope and consequence. Add the type of customer, system, volume, constraint, improvement, or deliverable. When a role genuinely consisted of routine responsibilities, show reliability, complexity, service standard, or a process contribution without manufacturing dramatic impact."),
        ("Using unsupported keywords", "Keyword stuffing can make a resume sound unnatural and create difficult interview questions. A skill list should be supported by a role, project, education, or certification. Hidden white text, copied job descriptions, and inflated expertise risk credibility and may violate application terms. Use the employer's phrase only when it accurately names your experience, and demonstrate it in context wherever possible."),
        ("Choosing fragile formatting", "Multiple columns, floating objects, charts, icons, headshots, and information embedded in images can disrupt reading order. Tiny fonts and compressed margins make a document unpleasant even when software extracts it. Keep an ATS-oriented version simple. Designers and other visual professionals can link to a portfolio or maintain a separate networking version without making the application file difficult to parse."),
        ("Ignoring basic consistency", "Mismatched dates, changing punctuation, unexplained abbreviations, inconsistent capitalization, and broken links suggest weak attention to detail. A wrong phone number can end an otherwise strong application. Verify contact details, employer names, degrees, dates, and claims against reliable records. Name the file professionally and remove tracked changes, comments, template instructions, and outdated metadata before submission."),
        ("Trusting a score more than judgment", "No public checker knows the employer's complete process. Chasing a percentage can encourage repetition and distract from qualification gaps. Use automated feedback to find missing sections, weak evidence, or relevant language, then make a human decision. Ask whether the resume is truthful, whether the intended role is obvious, whether the strongest evidence is easy to find, and whether every sentence earns its space."),
    ]),
    "tailor-resume-job-description": ("How to Tailor a Resume for a Job Description", "Use a repeatable process to analyze a job description and tailor resume evidence without exaggerating or stuffing keywords.", "Match the opportunity by selecting better evidence—not by rewriting your history.", [
        ("Read for structure before keywords", "Read the posting once for the business problem and again for details. Mark core responsibilities, required qualifications, preferred qualifications, tools, stakeholders, and outcomes. Notice repetition and the order of information. Separate genuine requirements from broad employer branding. This prevents a common mistake: collecting isolated keywords without understanding what the person will actually be hired to deliver."),
        ("Build a requirement-to-evidence map", "Create two columns outside the resume. On the left, list each important requirement in the employer's words. On the right, record a truthful example from work, projects, education, volunteering, or training. Add scale and outcome where known. Gaps become visible immediately. Some are wording gaps, where you have the experience but use a different term; others are qualification gaps that should not be disguised."),
        ("Choose the right document hierarchy", "Adjust the headline and summary so the target direction is clear. Move the most relevant skills earlier and position relevant projects where a recruiter can see them. Within each job, lead with the achievements connected to the new role. Older or unrelated work may need fewer bullets, but keep enough chronology to make the history understandable. Tailoring is partly subtraction: remove claims that consume space without supporting the decision."),
        ("Translate terminology carefully", "Employers may call the same practice account management, client success, or relationship management. Use the job's recognized term when it accurately describes your work, and pair it with evidence. Preserve important abbreviations and expanded names where helpful. Do not rename a former job title deceptively; if clarification is needed, add a functional descriptor without hiding the official title."),
        ("Revise bullets for the target", "A bullet can be true yet poorly targeted. For a project-management role, a software launch bullet should emphasize scope, stakeholders, risk, schedule, and delivery. For an engineering role, the same project may emphasize architecture, reliability, and technical decisions. Keep the factual core unchanged while selecting the dimension relevant to the reader. Quantify only with records or a reasonable statement you can explain in an interview."),
        ("Complete the application loop", "Compare the revised document with your evidence map. Confirm that mandatory qualifications are visible if you possess them and that important phrases appear naturally. Proofread the exported file and copy its text into a plain editor to check order. Save the job posting because it may disappear before an interview. Finally, prepare a few stories about the evidence you highlighted; successful tailoring should improve both the application and the later conversation."),
    ]),
    "resume-templates-guide": ("Resume Templates Guide", "Choose a resume template based on career stage, industry, ATS readability, content volume, and application context.", "Choose a structure that makes your evidence easier to see, not a design that competes with it.", [
        ("A template is a reading system", "A useful template establishes hierarchy, spacing, typography, and repeatable entry patterns. It should help a recruiter find identity, role direction, experience, dates, skills, and education without learning a new visual language. The template cannot decide which evidence matters or make generic writing credible. Start with content and target role, then choose the least complicated structure that presents that content well."),
        ("Modern and professional styles", "A modern template can use clean sans-serif typography, generous white space, and restrained accent color while keeping a single reading column. A professional template is intentionally conservative and works across finance, operations, health, administration, and corporate roles. Both should use ordinary text, familiar headings, and consistent dates. The difference is tone, not ATS compatibility."),
        ("Minimal and executive styles", "Minimal templates reduce visual elements and suit concise, evidence-rich applications. They demand careful editing because weak content has nowhere to hide. Executive templates need room for leadership scope, enterprise outcomes, board or stakeholder exposure, and selected career history. An executive document may reach two pages, but it should not become a complete biography. Strategic relevance still controls inclusion."),
        ("Templates for creative work", "A graphic designer, marketer, or product designer may want more personality. Keep the application resume structurally dependable and link to a portfolio where visual craft can be evaluated properly. If a networking version uses columns or graphics, maintain a separate ATS-oriented version. A photo is unnecessary in many markets and can create legal or bias concerns; follow local conventions and explicit instructions."),
        ("Evaluate before committing", "Paste realistic content into the template rather than judging an empty sample. Test long employer names, two-line bullets, multiple roles, links, and a second page. Check that text remains selectable and reading order stays sensible after PDF export. Confirm that the template does not use floating text boxes for important content. If maintaining the layout becomes a constant formatting struggle, choose a simpler system."),
        ("Make the design consistent", "Use one type family or a deliberate heading companion, a controlled size scale, uniform bullet style, and repeatable spacing. Align dates consistently and avoid excessive lines or decorative shapes. Do not solve overflow by shrinking below comfortable reading size. Edit low-value content first. ClearCV uses a single-column professional structure because it travels reliably between browser preview, editable DOCX, and text-based PDF."),
    ]),
    "cover-letter-guide": ("Cover Letter Guide", "Write a tailored cover letter that connects employer needs with specific evidence without repeating the resume.", "Add context and motivation that a resume cannot communicate on its own.", [
        ("Know what the letter must do", "A cover letter should explain why this work, why this organization, and why your evidence deserves a conversation. It is not a prose copy of the resume or a place for unsupported enthusiasm. Read the posting and credible information about the organization. Identify one or two central needs, then choose examples that show how you have addressed comparable problems."),
        ("Open with direction", "Use the correct role title and state a specific connection to the opportunity. A referral, relevant product, mission, market, or problem can provide context when genuine. Avoid theatrical openings and generic claims that the company is “prestigious.” The first paragraph should quickly establish what you offer and why the application is deliberate rather than mass-produced."),
        ("Develop evidence in the middle", "One or two body paragraphs are usually enough. Describe a relevant situation, your action, and the outcome, then connect that experience to the employer's need. Select evidence rather than summarizing every position. Details such as scale, stakeholder complexity, customer type, constraint, and verified result make the argument credible. Use a confident tone without presenting team results as yours alone."),
        ("Show informed motivation", "Explain what attracts you to the actual work: the users served, technical challenge, operating model, growth stage, public mission, or responsibility described. Refer only to facts you can verify and avoid excessive praise. Motivation is stronger when tied to experience or future contribution—for example, an interest in accessible services supported by prior accessibility work."),
        ("Close professionally", "Reinforce the fit in one sentence, express interest in a conversation, and thank the reader. Do not demand a response or repeat contact details excessively. Use a professional greeting and sign-off. If no hiring manager is identifiable through a reliable source, a neutral greeting such as “Dear Hiring Team” is better than guessing a person's identity."),
        ("Edit and deliver", "Keep the letter concise, usually one page, with formatting consistent with the resume. Remove filler, clichés, and sentences that merely announce passion. Verify the organization name, role title, recipient, dates, and attachment names—errors caused by reusing another letter are especially damaging. Follow application instructions, export a text-based file, and retain a copy of the posting and final letter for interview preparation."),
    ]),
    "interview-preparation-guide": ("Interview Preparation Guide", "Prepare credible interview stories, role research, questions, and follow-up using your tailored resume and job description.", "Turn the evidence in your resume into clear, confident conversations.", [
        ("Start from the hiring need", "Re-read the job description and group requirements into themes such as technical delivery, customer work, analysis, leadership, or operations. Research the organization's products, customers, recent official updates, and operating context using reliable sources. Write a short hypothesis about the problems this role may solve. Treat it as a question to explore, not a fact you already know."),
        ("Audit your submitted materials", "Use the exact resume and cover letter sent for this application. Highlight every claim, tool, metric, and project that could invite a question. Confirm dates and your individual contribution. If a result was shared, be ready to explain the team and your part. Prepare a plain-language explanation of technical terms for non-specialist interviewers and deeper detail for functional experts."),
        ("Build a story bank", "Prepare several examples covering achievement, conflict, failure, prioritization, ambiguity, collaboration, customer insight, and learning. A useful structure gives context, states your responsibility, describes specific actions, and ends with result and reflection. Do not memorize a script word for word. Remember the turning points and evidence so the answer remains natural and can adapt to different questions."),
        ("Practice realistic delivery", "Say answers aloud and time them. Lead with the answer before background, keep early context brief, and pause instead of filling silence. Record a practice session to notice speed, jargon, and repetitive phrases. For remote interviews, test the link, audio, camera, lighting, display name, and a backup connection. For onsite meetings, confirm route, arrival instructions, accessibility needs, and contact details."),
        ("Prepare thoughtful questions", "Ask questions that help you evaluate the work and demonstrate attention: priorities in the first months, measures of success, team interfaces, decision authority, current obstacles, feedback practices, and why the role is open. Avoid asking only what a public page answers. Interviews are mutual assessment; consider management quality, workload, values in practice, development, compensation process, and any personal nonnegotiables."),
        ("Follow up and learn", "Send a concise thank-you when appropriate, referring to a meaningful part of the discussion and reiterating relevant interest. Complete requested tasks on time and clarify scope before investing extensive unpaid effort. Record questions, strong answers, weak moments, and new information while memory is fresh. Do not interpret a delay as a verdict; continue other applications and follow the employer's stated timeline before checking in."),
    ]),
}

# Expanded editorial context added to every guide. Combined with the six unique
# sections above, each guide exceeds 800 words while retaining topic-specific copy.
GUIDE_CLOSERS = [
    ("Keep the process evidence-based", "Good career documents are built from records, not invention. Keep a private achievement log containing project goals, your actions, approved results, dates, tools, stakeholder groups, and lessons. Performance reviews, project notes, calendars, and public work samples can refresh memory. Respect confidentiality and remove personal or commercially sensitive information. When a claim cannot be supported or comfortably explained in an interview, rewrite it more precisely. This discipline improves resumes, cover letters, applications, and interviews at the same time."),
    ("Use tools with judgment", "Automation can compare language, flag missing sections, and format a document consistently, but it cannot verify a career story on its own. Review every suggestion for truth, relevance, tone, and local convention. Avoid publishing private job-description content when it is marked confidential. Keep control of the final wording and retain editable copies. ClearCV's readiness review is deliberately transparent: it points to visible factors and leaves the decision with the candidate rather than presenting an unexplained prediction."),
    ("Review from the employer's perspective", "Set the document aside briefly, then return as a reader who knows only the vacancy. Can that person identify the candidate's direction, recent scope, core capabilities, and strongest results without decoding jargon? Is important evidence supported by dates and context? Does the first page answer the most likely screening questions? Remove repetition, explain an uncommon abbreviation once, and move decisive evidence earlier. This reader-focused pass is often more valuable than adding another adjective or visual element."),
    ("Maintain a repeatable application workflow", "Use consistent filenames and keep a folder containing the posting, tailored resume, cover letter, application date, and follow-up notes. Record which evidence was emphasized so interview preparation matches the submitted version. Update the master history when a project ends rather than waiting for the next job search. A repeatable system reduces errors such as sending the wrong employer name, losing a useful metric, or preparing from an outdated document. Quality improves when the process is sustainable, not rushed."),
    ("Apply an ethical final check", "Before submission, ask whether every statement is accurate, proportionate, and yours to share. Distinguish personal contribution from team achievement and never change dates or titles to conceal the record. Remove confidential names, internal financial detail, and personal information about colleagues or customers. Confirm that links lead to work you are permitted to publish. Ethical editing is not only a matter of principle; it creates a document you can discuss calmly and consistently when an interviewer asks for detail. A final factual review also protects professional relationships and makes future updates much easier."),
]


PROFESSIONS = {
    "flutter-developer-resume": ("Flutter Developer Resume", "Flutter Developer", "mobile applications", "Dart, Flutter, state management, REST APIs, testing, CI/CD, Firebase, accessibility", "startup time, crash-free sessions, frame performance, release frequency, app rating", "Delivered cross-platform features from shared Dart code while improving release reliability across Android and iOS."),
    "software-engineer-resume": ("Software Engineer Resume", "Software Engineer", "reliable software systems", "system design, APIs, databases, testing, cloud infrastructure, observability, security", "latency, throughput, availability, deployment frequency, defect rate", "Designed maintainable services and improved production reliability through testing, monitoring, and focused technical decisions."),
    "accountant-resume": ("Accountant Resume", "Accountant", "accurate financial operations", "financial reporting, reconciliation, general ledger, audit support, ERP systems, controls, tax compliance", "close time, reconciliation volume, error reduction, audit findings, portfolio value", "Strengthened month-end reporting and account accuracy through disciplined reconciliation and documented controls."),
    "sales-representative-resume": ("Sales Representative Resume", "Sales Representative", "sustainable revenue growth", "prospecting, discovery, CRM, pipeline management, negotiation, forecasting, account development", "quota attainment, revenue, conversion, deal size, retention, pipeline value", "Built qualified pipeline and converted customer needs into appropriate solutions through structured discovery and follow-up."),
    "project-manager-resume": ("Project Manager Resume", "Project Manager", "predictable cross-functional delivery", "planning, risk management, budgeting, stakeholder communication, Agile, vendor management, governance", "on-time delivery, budget variance, cycle time, risk reduction, program value", "Led cross-functional delivery by clarifying scope, managing risk, and keeping decisions visible to stakeholders."),
    "graphic-designer-resume": ("Graphic Designer Resume", "Graphic Designer", "clear visual communication", "brand systems, typography, Adobe Creative Suite, Figma, production, art direction, accessibility", "campaign reach, production time, engagement, asset volume, brand adoption", "Created consistent visual systems and campaign assets that improved production efficiency without sacrificing craft."),
    "customer-service-resume": ("Customer Service Resume", "Customer Service Professional", "reliable customer support", "case management, de-escalation, CRM, product knowledge, documentation, quality assurance", "CSAT, response time, resolution time, case volume, first-contact resolution", "Resolved complex customer issues with empathy, accurate documentation, and dependable follow-through across support channels."),
    "marketing-specialist-resume": ("Marketing Specialist Resume", "Marketing Specialist", "measurable audience growth", "campaign planning, content, analytics, SEO, email, paid media, segmentation, brand", "qualified leads, conversion, engagement, acquisition cost, organic traffic", "Planned and measured integrated campaigns that connected audience insight with qualified growth."),
}


TEMPLATES = {
    "modern-resume-templates": ("Modern Resume Templates", "Modern", "clean sans-serif typography, generous white space, and restrained visual accents", "technology, product, digital operations, and contemporary business roles"),
    "professional-resume-templates": ("Professional Resume Templates", "Professional", "conservative hierarchy, familiar headings, and highly consistent spacing", "finance, administration, healthcare, education, law, and corporate environments"),
    "minimal-resume-templates": ("Minimal Resume Templates", "Minimal", "essential typography, limited rules, and no decorative competition", "candidates with concise, strong evidence in almost any field"),
    "executive-resume-templates": ("Executive Resume Templates", "Executive", "leadership scope, enterprise outcomes, selected career history, and strategic emphasis", "directors, vice presidents, general managers, and senior functional leaders"),
}


EXAMPLES = {
    "resume-before-after": ("Resume Before vs After Optimization", "See how vague resume content becomes specific, credible, and easier to scan without inventing information.", [
        ("Before: duty without context", "Responsible for customer emails and solving problems."),
        ("After: scope and outcome", "Resolved 45–60 weekly billing and account cases across email and chat, maintaining accurate CRM notes and improving first-contact resolution through a shared response guide."),
        ("Why it improves", "The revision identifies volume, issue type, channels, documentation practice, and a process contribution. The candidate should include the figures only when records or a defensible estimate support them."),
        ("Before: generic collaboration", "Worked with the team on a new application."),
        ("After: role and delivery", "Partnered with design, API, and QA colleagues to release the application's onboarding flow, documenting acceptance criteria and resolving launch-blocking defects before production."),
        ("Method", "Ask what was delivered, who was involved, what you personally did, what constraint mattered, and what changed. Preserve the facts while removing vague filler."),
    ]),
    "ats-optimization-examples": ("ATS Optimization Examples", "Practical examples of clearer headings, job terminology, skill evidence, dates, and ATS-readable formatting.", [
        ("Heading improvement", "Replace a creative heading such as “Where I Made an Impact” with “Professional Experience.” The content does not change, but both software and people can identify the section immediately."),
        ("Terminology improvement", "A posting asks for customer relationship management experience. If truthful, write “customer relationship management (CRM)” once and name the actual platform in a supported skill or achievement."),
        ("Evidence improvement", "Move “SQL” from an unsupported keyword list into context: “Built SQL quality checks that identified incomplete order records before the weekly operations report.”"),
        ("Formatting improvement", "Replace a two-column skills sidebar and icon-based contact block with selectable text in one reading column. Keep portfolio design in a linked work sample."),
        ("Testing improvement", "After export, copy all PDF text into a plain editor and confirm that the name, contact details, roles, employers, dates, and bullets appear in the intended order."),
    ]),
    "resume-tailoring-examples": ("Resume Tailoring Examples", "See how one truthful career history can emphasize different evidence for different job descriptions.", [
        ("Base experience", "A coordinator organized a product launch, updated dashboards, handled vendor schedules, and documented customer feedback. Every tailored version must keep those facts intact."),
        ("For a project coordinator role", "Lead with schedule ownership, dependency tracking, vendor coordination, status reporting, and launch risks. The summary can emphasize cross-functional delivery and operational follow-through."),
        ("For a marketing operations role", "Lead with launch campaign coordination, dashboard reporting, customer insight synthesis, and collaboration with creative or channel owners. Do not add campaign tools that were never used."),
        ("For a customer success role", "Lead with customer feedback patterns, issue documentation, communication, and how insight affected the launch. Keep internal project detail only where it supports customer outcomes."),
        ("The rule", "Tailoring changes selection, order, and vocabulary—not employers, dates, credentials, or results. Save each version with the job posting so you can prepare for the interview from the exact claims submitted."),
    ]),
}


def build_guide_pages():
    pages = {}
    slugs = list(GUIDE_SPECS)
    for index, (slug, (title, description, intro, sections)) in enumerate(GUIDE_SPECS.items()):
        related = [slugs[(index + 1) % len(slugs)], slugs[(index + 3) % len(slugs)], "faq"]
        pages[slug] = page(title, description, "Career Guide", intro, sections + GUIDE_CLOSERS, related)
    return pages


def build_profession_pages():
    pages = {}
    slugs = list(PROFESSIONS)
    for i, (slug, (title, role, purpose, skills, metrics, example)) in enumerate(PROFESSIONS.items()):
        pages[slug] = page(title, f"Create an ATS-friendly {role.lower()} resume with relevant skills, achievement examples, structure, and tailoring guidance.", "Resume by Profession",
            f"A strong {role.lower()} resume connects real experience to {purpose}. Use this guide to choose evidence, terminology, and metrics without copying generic content.", [
                (f"What employers need from a {role}", f"Start with the outcomes described in the posting, not a generic list of traits. Identify the environments, customers, systems, constraints, and collaborators involved in the work. Build a requirement-to-evidence map and make the strongest supported match visible in the summary and first experience bullets."),
                ("Skills to demonstrate", f"Relevant terms may include {skills}. A keyword belongs on the resume only when you can explain how and where you used it. Place important capabilities in context within achievements; use the skills section as a concise index rather than the only evidence."),
                ("Results and scope", f"Useful measures may include {metrics}. Verify every figure. If a commercial number is confidential or unavailable, describe the delivered change, operating scale, stakeholder adoption, quality improvement, or documented process result."),
                ("Example positioning", example + " This sentence is a structural example, not content to copy. Replace it with your actual action, environment, scope, and outcome."),
                ("Recommended structure", "Use a specific professional summary, core skills, reverse-chronological experience, selected projects when relevant, and education or certifications. Keep one main column, ordinary headings, selectable text, consistent dates, and a professional filename. Link to a portfolio only when it adds credible evidence."),
                ("Tailoring checklist", f"Confirm that the exact {role.lower()} title is clear, mandatory qualifications are visible when possessed, and the first half of the page contains the strongest evidence. Compare the exported text with the job description, remove unsupported language, proofread links and dates, and prepare to discuss every highlighted result."),
            ], related=(slugs[(i+1)%len(slugs)], "tailor-resume-job-description", "resume-templates-guide"))
    return pages


def build_template_pages():
    pages = {}
    slugs = list(TEMPLATES)
    for i, (slug, (title, style, design, audience)) in enumerate(TEMPLATES.items()):
        pages[slug] = page(title, f"Explore {style.lower()} resume template principles, ATS considerations, content hierarchy, and selection guidance.", "Template Collection",
            f"{style} resume templates use {design}. The right choice supports the content and application context instead of drawing attention away from qualifications.", [
                ("Design character", f"This collection is defined by {design}. It is especially useful for {audience}. Personality comes from controlled typography and spacing rather than icons, skill bars, photos, or complicated page construction."),
                ("ATS considerations", "Keep essential information in one primary reading column with standard headings and selectable text. Avoid placing contact details in a page header, embedding words in graphics, or using floating boxes. A polished document can remain technically straightforward."),
                ("Content hierarchy", "Lead with identity and role direction, then place the most persuasive evidence according to career stage. Experienced candidates usually prioritize professional experience. Recent graduates may raise education and projects. Skills should summarize demonstrated capabilities rather than replace dated evidence."),
                ("When to choose it", f"Choose a {style.lower()} template when its tone matches the employer and your content volume fits without artificial compression. Test long lines, multiple roles, and a second page. The template should remain stable after editing and export."),
                ("How to customize", "Change content before decoration. Use a restrained color only if appropriate, keep comfortable font sizes, align dates consistently, and preserve spacing patterns. Export DOCX when editing or employer instructions favor it; export a text-based PDF when appearance must remain fixed."),
            ], related=(slugs[(i+1)%len(slugs)], "resume-templates-guide", "ats-resume-guide"))
    return pages


GUIDE_PAGES = build_guide_pages()
PROFESSION_PAGES = build_profession_pages()
TEMPLATE_PAGES = build_template_pages()
EXAMPLE_PAGES = {slug: page(title, description, "Resume Examples", description, sections,
    ("ats-resume-guide", "tailor-resume-job-description", "common-resume-mistakes")) for slug, (title, description, sections) in EXAMPLES.items()}
ALL_PAGES = {**POLICY_PAGES, **GUIDE_PAGES, **PROFESSION_PAGES, **TEMPLATE_PAGES, **EXAMPLE_PAGES}


def rebrand(value):
    if isinstance(value, str):
        return value.replace("support@clearcv.example", "support@atsforge.example").replace("ClearCV", "ATSForge")
    if isinstance(value, tuple):
        return tuple(rebrand(item) for item in value)
    if isinstance(value, list):
        return [rebrand(item) for item in value]
    if isinstance(value, dict):
        return {key: rebrand(item) for key, item in value.items()}
    return value


ALL_PAGES = rebrand(ALL_PAGES)

NAV_GROUPS = {
    "Company": ["about", "contact", "pricing", "faq"],
    "Guides": list(GUIDE_PAGES),
    "Resume Examples": list(PROFESSION_PAGES),
    "Templates": list(TEMPLATE_PAGES),
    "Optimization": list(EXAMPLE_PAGES),
    "Legal": ["privacy-policy", "terms", "refund-policy"],
}
