name: atsforge_application
description: "The native ATSForge resume builder and tailoring application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  get_it: ^7.7.0
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/atsforge_logo.png
  adaptive_icon_background: "#F8F6F0"
  adaptive_icon_foreground: assets/images/atsforge_logo.png
  adaptive_icon_foreground_inset: 22
  remove_alpha_ios: true
  background_color_ios: "#F8F6F0"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/atsforge_logo.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/atsforge_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: false
  android_12:
    color: "#FFFFFF"
    image: assets/images/atsforge_splash_android12.png
    color_dark: "#FFFFFF"
    image_dark: assets/images/atsforge_splash_android12.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"